apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
    spec:
      containers:
        - name: mon-app
          image: ouabou2003/my-springboot-app
          #imagePullPolicy: Never
          ports:
            - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: mon-app-service
spec:
  type: NodePort
  selector:
    app: mon-app
  ports:
    - protocol: TCP
      port: 8080         # Port du service
      targetPort: 8080   # Port exposé dans ton conteneur
